# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title
# pretty
# relative_permalinks: true

# Setup
title:            Juan Francisco Saldarriaga
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
# baseurl:          http://juanfrans.github.io/

# Required if you want to move pages into a a separate directory
include: ['_pages']
relative_permalinks: false

author:
  name:           'Juan Francisco Saldarriaga'
  url:            https://twitter.com/juanfrans

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/juanfrans/juanfrans.github.io
