# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Juan Francisco Saldarriaga
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
# baseurl:          http://juanfrans.github.io/

author:
  name:           'Juan Francisco Saldarriaga'
  url:            https://twitter.com/juanfrans

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/juanfrans/juanfrans.github.io
