

# Site settings
title: Juan Francisco Saldarriaga
email: juanfrans@gmail.com
github: https://github.com/juanfrans
twitter: https://twitter.com/juanfrans
author: Juan Francisco Saldarriaga
description: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: https://juanfrans.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Required if you want to move pages into a a separate directory
include: ['_pages']
relative_permalinks: false

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
